highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://schw4b.github.io
author: Simon Schwab

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Simon Schwab
name: Simon Schwab
email: simon.schwab@bdi.ox.ac.uk
email_full: mailto:simon.schwab@bdi.ox.ac.uk
website: schw4b.github.io
website_full: https://schw4b.github.io
github: schw4b
twitter: SimonSchw4b
# tel: +44 (0)24 7657 3665
# tel_full: tel:+440000000000
google_maps: 'https://www.google.co.uk/maps/place/Big+Data+Institute/@51.7526032,-1.2173949,17z/data=!4m13!1m7!3m6!1s0x4876c165dcbdeda5:0x11ccdb69263692a0!2sOxford+OX3+7LF!3b1!8m2!3d51.7526181!4d-1.2150892!3m4!1s0x0:0x97dc52c306a9f71d!8m2!3d51.752769!4d-1.2148999?hl=en'
address: University of Oxford
postcode: OX3 7LF
city: Oxford
country: United Kingdom
google_analytics: UA-72106507-1

# needed for travis-ci build
exclude: [vendor]
