highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://schw4b.github.io
author: Simon Schwab

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: Byungju Kim
name: Byungju Kim
email: byungju.kim@kaist.ac.kr
email_full: mailto:peyton.kim@mathpresso.com
email_full_kaist: mailto:byungju.kim@kaist.ac.kr
website: feidfoe.github.io
website_full: https://feidfoe.github.io
github: feidfoe
# tel: +44 (0)24 7657 3665
# tel_full: tel:+440000000000
google_maps: 'https://goo.gl/maps/yZctsHukQyBHa9Dt8'
department: Department of Electric Engineering
institution: Mathpresso Inc
country: Korea, Republic of
google_analytics: UA-72106507-1
institute_web: 'https://www.kaist.ac.kr/html/en/index.html'
department_web: 'https://ee.kaist.ac.kr/?language=en'


# needed for travis-ci build
exclude: [vendor]
